### ISSUE TITLE
Object analyzer exceptions

### ISSUE THREAD

**Issue by AngheloAlf** [Random06457/Z64Utils#16]
The object analyzer throws an exception when trying to analyze some objects.

I'll list the ones I found. If I found more, then I'll edit this post to add them.

- `object_hata`
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Z64.Z64Object.AddFrameData(Int32 count, String name, Int32 off)
   at Z64.Z64ObjectAnalyzer.FindAnimations(Z64Object obj, Byte[] data, Int32 segmentId)
   at Z64.Z64ObjectAnalyzer.AnalyzeDlists(Z64Object obj, Byte[] data, Int32 segmentId)
   at Z64.Forms.ObjectAnalyzerForm.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**Comment by EllipticEllipsis** [comment]
`object_hata`'s problem relates to the collision at the start of the file: I zeroed the bytes for the collision header and it worked fine to extract everything else. Hylian Toolbox is also confused, although to a lesser extent: it sees an animation at `0xD4` which isn't actually real.
